Implement modal saved functionality
jsoderholm/dynfin pull request #58
Opened 2024-04-27 16:16 UTC by sara-str

2024-04-27 16:30 UTC, jsoderholm commented on src/presenters/browse-presenter.tsx
> +
```suggestion
```
Måste ha blivit något fel här. Logiken finns redan ovanför

2024-04-27 16:31 UTC, jsoderholm requested changes
Det verkar som att du har skrivit samma logik två gånger. Annars toppen :+1:

2024-04-29 11:41 UTC, jsoderholm commented
Kika på den [här](https://ui.shadcn.com/docs/components/dialog)! Komponenten heter `Dialog` istället för `Modal`, men det är precis samma sak. Jag har bland annat använt den för `user-auth-modal.tsx`, så du kan kika där för att se hur den fungerar :+1: @sara-str

2024-04-30 14:38 UTC, sara-str commented
reviewa gärna! @jsoderholm @PushingCoder572 @carlhansson

2024-04-30 15:11 UTC, jsoderholm commented on src/views/browse-view.tsx
>        <CardContent>
```suggestion
      <CardContent className="flex-grow">
```

2024-05-02 07:11 UTC, jsoderholm commented on src/views/browse-view.tsx
> +            </DropdownMenuItem>
Ta bort detta och ersätt med `DropdownMenuLabel`

2024-05-02 07:12 UTC, jsoderholm commented on package.json
> +    "@shadcn/ui": "^0.0.4",
```suggestion
```

2024-05-02 07:14 UTC, jsoderholm commented on src/views/browse-view.tsx
> +                    handleToggleFavorite
Så va?
```suggestion
                    handleToggleFavorite()
```

2024-05-15 13:43 UTC, jsoderholm commented
Är denna fortfarande relevant? Om inte så kan du stänga den. @sara-str

2024-05-16 12:35 UTC, closed without merging