Read more modal
jsoderholm/dynfin pull request #77
Opened 2024-05-02 12:53 UTC by sara-str

2024-05-03 13:13 UTC, jsoderholm commented
Bör inte `news-modal.tsx` visa all information som finns tillgänglig? Varje `BrowseItem` kan skicka vidare sin `info` prop till modalen @sara-str :+1:

2024-05-05 13:53 UTC, jsoderholm requested changes
Snyggt! Jag tycker fortfarande att vi kan använda `Badge` för att visa en ticker, samt att dessa även bör finnas med i modalen, men det är min personliga preferens. Utöver det var det endast några småsaker :+1: @sara-str

2024-05-05 13:53 UTC, jsoderholm commented on src/lib/api/stock-news.ts
> +    items: '100',
Vi bör inte hämta 100 stycken på en och samma gång.

```suggestion
    items: '12',
```

2024-05-05 13:53 UTC, jsoderholm commented on src/views/browse-view.tsx
>      <Card>
```suggestion
    <Card className="flex flex-col">
```

2024-05-05 13:53 UTC, jsoderholm commented on src/views/browse-view.tsx
>        <CardContent>
```suggestion
      <CardContent className="flex-grow">
```

2024-05-05 13:53 UTC, jsoderholm commented on src/components/news-modal.tsx
> +        <Button variant='ghost'>Read more</Button>
```suggestion
        <Button>Read more</Button>
```

2024-05-05 13:53 UTC, jsoderholm commented on src/views/browse-view.tsx
> +            <Button variant='ghost'>Tickers</Button>
```suggestion
            <Button variant='secondary'>Tickers</Button>
```

2024-05-05 13:53 UTC, jsoderholm commented on src/views/browse-view.tsx
>        <CardFooter className='flex items-center justify-center'>
```suggestion
      <CardFooter className='grid sm:grid-cols-2 gap-6'>
```

2024-05-06 10:19 UTC, sara-str commented
reviewa gärna! @jsoderholm @carlhansson @PushingCoder572

2024-05-06 12:30 UTC, jsoderholm approved these changes
Snyggt! Just nu fungerar det inte att trycka på "favorite" i `Dropdown`, på grund av att samma värde på `favorited` används till samtliga tickers. Jag approvar den här, så kan vi fixa det senare :+1:

2024-05-06 12:31 UTC, merged